### ISSUE TITLE
module 'os' has no attribute 'popen2'

### ISSUE THREAD

**Issue by mayermart** [metalink-dev/pymetalink#34]
Hi,

i would like to use your library to download data with a meta4 file.
Unfortunately i get a error when adding metalink.download to the import.

```
import os.path
import metalink.download

if __name__ == '__main__':
    files = metalink.download.get("file.meta4", os.getcwd())
```

The Error i get:

```
Traceback (most recent call last):
  File "C:\path\.venv\Lib\site-packages\metalink\download.py", line 95, in <module>
    import proxy
ModuleNotFoundError: No module named 'proxy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\path\.venv\Lib\site-packages\metalink\proxy.py", line 177, in get_key_value
    keyid = win32api.RegOpenKeyEx(win32con.HKEY_CURRENT_USER, key)
            ^^^^^^^^
NameError: name 'win32api' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\path\test.py", line 3, in <module>
    import metalink.download
  File "C:\path\.venv\Lib\site-packages\metalink\download.py", line 97, in <module>
    from . import proxy
  File "C:\path\.venv\Lib\site-packages\metalink\proxy.py", line 253, in <module>
    get_proxy_info()
    ~~~~~~~~~~~~~~^^
  File "C:\path\.venv\Lib\site-packages\metalink\proxy.py", line 223, in get_proxy_info
    proxy_enable = get_key_value(
        "Software\\Microsoft\\Windows\\CurrentVersion\\Internet Settings", "ProxyEnable"
    )
  File "C:\path\.venv\Lib\site-packages\metalink\proxy.py", line 183, in get_key_value
    stdout = reg_query("HKCU\\" + key, value)
  File "C:\path\.venv\Lib\site-packages\metalink\proxy.py", line 137, in reg_query
    tempresult = os.popen2(f'reg.exe query "{keyname}" /v "{value}"')
                 ^^^^^^^^^
AttributeError: module 'os' has no attribute 'popen2'. Did you mean: 'popen'?
```

Tested with Python 3.12.7 and 3.13.0 (with and without venv)

Thanks for your assistance.

**Comment by mayermart** [comment]
As far as I understand, proxy.py classes are written for Python 2. 
Should Python 2 still be supported by this project?

**Comment by bneijt** [comment]
I think you are right, this is really old code that has never been ported to a newer version of Python. Feel ree to start a pr, my time is very limited so I probably won’t be able to do that any time soon. Sorry for the inconvenience

**Comment by mayermart** [comment]
Thanks for your response.
I already made some adjustments [here](https://github.com/mayermart/pymetalink/tree/fix-proxy) to make it run on my environment.
Can I remove the python 2 support, or should it still be supported?

**Comment by bneijt** [comment]
Feel free to remove python 2, I think given the long sleeps between maintenance we have, we should probably target 312 atm and forget about other versions ;)
