### ISSUE TITLE
download.get does not work on Python 3.6 or newer

### ISSUE THREAD

**Issue by cehbrecht** [metalink-dev/pymetalink#5]
Running the following code on Python 3.6:

```
from metalink import download
url = 'http://localhost:5000/outputs/c25b4b8c-57b3-11e9-9cc5-acde48001122/input.meta4'
download.get(url, path='/tmp')
```

I get the following exception:
```
Metalink content-type detected.
Downloading to /tmp/input_uxopijn7.txt.
Exception in thread Thread-609:
Traceback (most recent call last):
  File "/Users/pingu/.conda/envs/metalink/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/pingu/Documents/GitHub/birdhouse/pymetalink/metalink/download.py", line 2092, in run
    self.host.conn.request("GET", self.url, "", self.headers)
  File "/Users/pingu/.conda/envs/metalink/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
TypeError: _send_request() takes 5 positional arguments but 6 were given
```

The  referenced meta4 file is just a dummy example:
```
<?xml version="1.0" encoding="UTF-8"?>
<metalink xmlns="urn:ietf:params:xml:ns:metalink">
  <published>2019-04-05T17:01:58Z</published>
  <generator>PyWPS/4.3.dev0</generator>

  <file name="input_43wk43lx.txt">
    <identity>output_0</identity>
    <size>9</size>
    <hash type="sha-256"></hash>
    <metaurl mediatype="text/plain">http://localhost:5000/outputs/c2671c82-57b3-11e9-8b79-acde48001122/input_43wk43lx.txt</metaurl>
  </file>
  <file name="input_go_5eksm.txt">
    <identity>output_1</identity>
    <size>9</size>
    <hash type="sha-256"></hash>
    <metaurl mediatype="text/plain">http://localhost:5000/outputs/c2675166-57b3-11e9-b912-acde48001122/input_go_5eksm.txt</metaurl>
  </file>

</metalink>
```

**Comment by huard** [comment]
Using 
```download.get(url, path='/tmp', segmented=False)``` 
seems to avoid this issue.

**Comment by bneijt** [comment]
Thanks to @cehbrecht for the PR that fixes this issue. Please re-open if this issue still persists.
